# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo iniciando pipeline andressa
  displayName: 'pipeline lab andressa'

- script: |
      #       
      echo "A data de hoje : $(date "+%Y%m%d")"

- script: |
    echo laboratorio dataset portal transparencia
    echo link https://portaldatransparencia.gov.br/download-de-dados/ceis
  displayName: 'laboratorio 01 testando scripts shell'
