# Criar rotina automatizada para baixar dataset diaria CEIS
# LabDevOps Andressa Barros 
# andressa_barros18@hotmail.com

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: START_STAGE1
  jobs:
  - job: START_PIPELINE
    steps:
      - script: echo iniciando pipeline andressa
    displayName: 'pipeline lab andressa'

- stage: START_STAGE2      
  jobs:
  - job: FORMAT_DATE
    steps:
     - script: |
          #       
          echo "A data de hoje : $(date "+%Y%m%d")"

- stage: START_STAGE3
  jobs:
  - job: FINALIZANDO_ITEM
    steps:
      - script: |
          echo laboratorio dataset portal transparencia
          echo link https://portaldatransparencia.gov.br/download-de-dados/ceis
    displayName: 'laboratorio 01 testando scripts shell'
